const analyticsIndicators=[
  {name:"Cambriolages de logement",tone:"orange"},
  {name:"Violences physiques intrafamiliales",tone:"magenta"},
  {name:"Vols de véhicule",tone:"cyan"},
  {name:"Destructions et dégradations volontaires",tone:"gold"}
];
function parseAnalyticsCsv(text){const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/),head=lines.shift().split(";").map(x=>x.replaceAll('"',''));return lines.map(line=>{const v=line.split(";").map(x=>x.replace(/^"|"$/g,""));return Object.fromEntries(head.map((h,i)=>[h,v[i]]))}).filter(x=>x.Code_departement==="95")}
function analyticsBars(rows,tone){const max=Math.max(...rows.map(x=>+x.nombre));return `<div class="analytics-bars ${tone}">${rows.map(x=>`<div class="analytics-col"><b>${Number(+x.nombre).toLocaleString("fr-FR")}</b><i style="height:${Math.max(4,+x.nombre/max*132)}px"></i><small>${x.annee.slice(2)}</small></div>`).join("")}</div>`}
let analyticsReady=false;
async function renderAnalytics(){if(analyticsReady)return;const root=document.getElementById("analyticsContent");try{const [rows,competence,osm]=await Promise.all([fetch("data/ssmsi-departement.csv").then(r=>r.text()).then(parseAnalyticsCsv),fetch("data/competence-police-gendarmerie.csv").then(r=>r.text()),fetch("data/osm-services.json").then(r=>r.json())]);const comp=competence.split(/\r?\n/).slice(1).filter(x=>x.startsWith('"95')),pn=comp.filter(x=>x.includes(';"PN";')).length,gn=comp.filter(x=>x.includes(';"GN";')).length,services=osm.elements||[],fires=services.filter(x=>x.tags?.amenity==="fire_station").length,police=services.filter(x=>x.tags?.["police:FR"]==="police").length,gendarmerie=services.filter(x=>x.tags?.["police:FR"]==="gendarmerie").length,pnShare=(pn/(pn+gn)*100).toFixed(1);root.innerHTML=`<section class="analytics-kpis"><article class="analytics-kpi pn"><small>Communes zone police</small><strong>${pn}</strong><span>${pnShare.replace(".",",")} % des communes</span></article><article class="analytics-kpi gn"><small>Communes zone gendarmerie</small><strong>${gn}</strong><span>${(100-Number(pnShare)).toFixed(1).replace(".",",")} % des communes</span></article><article class="analytics-kpi forces"><small>Implantations PN · GN</small><strong>${police+gendarmerie}</strong><span>${police} police · ${gendarmerie} gendarmerie</span></article><article class="analytics-kpi fire"><small>Centres de secours OSM</small><strong>${fires}</strong><span>implantations recensées</span></article></section><section class="analytics-distribution"><div class="analytics-donut" style="--pn:${pnShare}%"><b>183</b><small>communes</small></div><div><span class="pn-line"><b>${pn}</b> communes en zone Police nationale</span><span class="gn-line"><b>${gn}</b> communes en zone Gendarmerie nationale</span></div></section><section class="analytics-grid">${analyticsIndicators.map(ind=>{const data=rows.filter(x=>x.indicateur===ind.name).sort((a,b)=>a.annee-b.annee);return `<article class="analytics-chart ${ind.tone}"><h3>${ind.name}</h3><p>Faits enregistrés · 2016–2025</p>${analyticsBars(data,ind.tone)}</article>`}).join("")}</section><p class="analytics-source"><strong>Lecture et sources.</strong> Faits enregistrés par la Police et la Gendarmerie nationales selon le lieu de commission ; ils ne mesurent pas toute la délinquance subie. SSMSI, juillet 2026 · OpenStreetMap, 10 août 2026.</p>`;analyticsReady=true}catch(e){root.innerHTML='<div class="analytics-loading">Les données sont momentanément indisponibles.</div>'}}
["openData","openDataTop"].forEach(id=>document.getElementById(id).addEventListener("click",()=>{document.getElementById("dataDialog").showModal();renderAnalytics()}));
