const fireStations=[["Argenteuil",49,2.25],["Beaumont-sur-Oise",49.14,2.29],["Bezons",48.93,2.22],["Cergy",49.04,2.06],["Deuil-la-Barre",48.98,2.33],["Domont",49.03,2.32],["Eaubonne",48.99,2.28],["Enghien-les-Bains",48.97,2.31],["Ermont",48.99,2.26],["Fosses",49.10,2.51],["Garges-lès-Gonesse",48.97,2.40],["Gonesse",48.99,2.45],["L’Isle-Adam",49.11,2.22],["Louvres",49.04,2.50],["Magny-en-Vexin",49.15,1.79],["Marines",49.14,1.98],["Montmorency",48.99,2.32],["Osny",49.07,2.06],["Persan",49.15,2.27],["Pontoise",49.05,2.10],["Roissy-en-France",49,2.52],["Saint-Ouen-l’Aumône",49.04,2.12],["Sarcelles",48.99,2.38],["Villiers-le-Bel",49.01,2.39]];
const state={police:true,gendarmerie:true,pompiers:true,communes:[],competences:new Map(),territory:null,markers:[]};
const map=L.map("map",{zoomControl:false}).setView([49.075,2.1],9);L.control.zoom({position:"bottomright"}).addTo(map);L.tileLayer("https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",{maxZoom:19,subdomains:"abcd",attribution:"© OpenStreetMap · © CARTO"}).addTo(map);
function parseCsv(text){return text.split(/\r?\n/).slice(1).map(line=>{const c=line.split(";").map(v=>v.replace(/^"|"$/g,""));return{code:c[0],institution:c[2],service:c[4]}}).filter(r=>r.code?.startsWith("95"))}
function style(feature){const police=feature.properties.competence?.institution==="PN",visible=police?state.police:state.gendarmerie;return{color:visible?(police?"#000091":"#18753c"):"#aeb7c5",weight:visible?1.2:.5,fillColor:visible?(police?"#6a6af4":"#88d39f"):"#eef1f5",fillOpacity:visible?.62:.18}}
function showDetail(feature,layer){const p=feature.properties,c=p.competence,force=c?.institution==="PN"?"Police nationale":"Gendarmerie nationale";document.getElementById("detailContent").innerHTML=`<span class="eyebrow">COMMUNE SÉLECTIONNÉE</span><h2>${p.nom}</h2><div class="detail-stat"><span>Force compétente</span><strong>${force}</strong></div><div class="detail-stat"><span>Unité de rattachement</span><strong>${(c?.service||"Information indisponible").replace(/^.*? - /,"")}</strong></div><p class="detail-help">En cas d’urgence, composez le <b>17</b> ou le <b>112</b>. L’unité affichée renseigne la compétence territoriale, pas nécessairement le lieu d’accueil le plus proche.</p><a class="detail-link" href="https://www.masecurite.interieur.gouv.fr/" target="_blank" rel="noopener">Trouver un point d’accueil ↗</a>`;document.getElementById("detailPanel").classList.add("open");map.fitBounds(layer.getBounds(),{maxZoom:11,padding:[40,380]})}
function render(){if(state.territory)map.removeLayer(state.territory);state.markers.forEach(m=>map.removeLayer(m));state.markers=[];const features=state.communes.filter(c=>c.contour).map(c=>({type:"Feature",properties:{...c,competence:state.competences.get(c.code)},geometry:c.contour}));state.territory=L.geoJSON({type:"FeatureCollection",features},{style,onEachFeature:(f,l)=>{l.bindTooltip(`<strong>${f.properties.nom}</strong><br>${f.properties.competence?.institution==="PN"?"Police nationale":"Gendarmerie nationale"}`,{sticky:true});l.on("click",()=>showDetail(f,l))}}).addTo(map);if(state.pompiers)fireStations.forEach(([name,lat,lng])=>{const m=L.circleMarker([lat,lng],{radius:6,color:"#fff",weight:2,fillColor:"#e1000f",fillOpacity:1}).bindTooltip(`<strong>Centre de secours</strong><br>${name}`).addTo(map);state.markers.push(m)});document.getElementById("mapStatus").textContent=`${state.communes.length} communes · cliquez sur la carte pour connaître le service compétent`}
Promise.all([fetch("https://geo.api.gouv.fr/departements/95/communes?fields=nom,code,centre,contour").then(r=>r.json()),fetch("data/competence-police-gendarmerie.csv").then(r=>r.text()).then(parseCsv)]).then(([communes,competences])=>{state.communes=communes;state.competences=new Map(competences.map(c=>[c.code,c]));render();map.fitBounds(state.territory.getBounds(),{padding:[20,20]})}).catch(()=>document.getElementById("mapStatus").textContent="Données momentanément indisponibles");
document.querySelectorAll("[data-layer]").forEach(button=>button.addEventListener("click",()=>{const key=button.dataset.layer;state[key]=!state[key];button.classList.toggle("active",state[key]);button.setAttribute("aria-pressed",String(state[key]));render()}));
document.getElementById("resetView").addEventListener("click",()=>state.territory&&map.fitBounds(state.territory.getBounds(),{padding:[20,20]}));document.getElementById("closeDetail").addEventListener("click",()=>document.getElementById("detailPanel").classList.remove("open"));
function search(){const q=document.getElementById("searchInput").value.trim().toLocaleLowerCase("fr"),c=state.communes.find(x=>x.nom.toLocaleLowerCase("fr").startsWith(q));if(!c)return;state.territory.eachLayer(l=>{if(l.feature.properties.code===c.code)showDetail(l.feature,l)})}document.getElementById("searchButton").addEventListener("click",search);document.getElementById("searchInput").addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();search()}});
const dialogs={openUrgences:"urgenceDialog",openComprendre:"comprendreDialog",openComprendreTop:"comprendreDialog"};Object.entries(dialogs).forEach(([id,target])=>document.getElementById(id).addEventListener("click",()=>document.getElementById(target).showModal()));document.querySelectorAll("[data-close]").forEach(b=>b.addEventListener("click",()=>document.getElementById(b.dataset.close).close()));
document.getElementById("mobileLayers").addEventListener("click",e=>{const sidebar=document.getElementById("layerSidebar"),open=sidebar.classList.toggle("open");e.currentTarget.setAttribute("aria-expanded",String(open))});
