const state={policeZone:false,gendarmerieZone:false,commissariats:false,brigades:false,pompiers:false,cspPolice:false,communes:[],competences:new Map(),services:[],territory:null,markers:[],elus:null,csp:null,cspLayer:null,communeCsp:new Map()};
function maskRings(geometry){const polys=geometry.type==="Polygon"?[geometry.coordinates]:geometry.coordinates,rings=[];polys.forEach(poly=>poly.forEach(ring=>rings.push(ring.map(([lng,lat])=>[lat,lng]))));return rings}
function addDeptMask(contour){if(!contour)return;const world=[[-89,-179],[89,-179],[89,179],[-89,179]];L.polygon([world,...maskRings(contour)],{stroke:true,color:"#070047",weight:1.6,opacity:.5,fillColor:"#070047",fillOpacity:.55,interactive:false}).addTo(map)}
function pointInRing(pt,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const xi=ring[i][0],yi=ring[i][1],xj=ring[j][0],yj=ring[j][1];const intersect=((yi>pt[1])!==(yj>pt[1]))&&(pt[0]<(xj-xi)*(pt[1]-yi)/(yj-yi)+xi);if(intersect)inside=!inside}return inside}
function pointInPolygon(pt,rings){if(!pointInRing(pt,rings[0]))return false;for(let k=1;k<rings.length;k++)if(pointInRing(pt,rings[k]))return false;return true}
function pointInGeometry(pt,geom){return geom.type==="Polygon"?pointInPolygon(pt,geom.coordinates):geom.coordinates.some(poly=>pointInPolygon(pt,poly))}
function cspStyle(){return{color:"#d49b00",weight:2,dashArray:"6 5",fillColor:"#d49b00",fillOpacity:.03,interactive:false}}
const map=L.map("map",{zoomControl:false}).setView([49.075,2.1],9);L.control.zoom({position:"bottomright"}).addTo(map);L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"}).addTo(map);
function parseCsv(text){return text.split(/\r?\n/).slice(1).map(line=>{const c=line.split(";").map(v=>v.replace(/^"|"$/g,""));return{code:c[0],institution:c[2],service:c[4]}}).filter(r=>r.code?.startsWith("95"))}
const sectorPalette=["#0b6e4f","#7b2cbf","#d1495b","#0077b6","#f77f00","#6a994e","#9c6644","#4361ee","#c2185b","#00897b","#8d6e00","#5e548e","#e76f51","#277da1","#7f5539"];
const sectorNames=[];
function shortService(service){return(service||"Secteur inconnu").replace("Gendarmerie - Brigade de ","").replace("Gendarmerie - Brigade d'","").replace("Gendarmerie - Brigade de l'","")}
function sectorColor(service){const index=Math.max(0,sectorNames.indexOf(service));return sectorPalette[index%sectorPalette.length]}
function style(feature){const c=feature.properties.competence,police=c?.institution==="PN",visible=police?state.policeZone:state.gendarmerieZone,color=police?"#000091":sectorColor(c?.service);return{color:visible?(police?"#000091":"#fff"):"#aeb7c5",weight:visible?(police?1.2:1.6):.5,fillColor:visible?(police?"#6a6af4":color):"#eef1f5",fillOpacity:visible?.68:.18}}
function cantonsForCommune(e,c){if(c.canton_code&&e.conseillers_departementaux[c.canton_code])return[e.conseillers_departementaux[c.canton_code]];if(!c.canton_nom)return[];return Object.values(e.conseillers_departementaux).filter(cd=>cd.nom===c.canton_nom||cd.nom.startsWith(c.canton_nom+"-"))}
function eluBlock(code){const e=state.elus,c=e?.communes?.[code];if(!e||!c)return"";const deputes=(c.circos||[]).map(id=>({num:parseInt(id.slice(2),10),nom:e.deputes["95"+String(parseInt(id.slice(2),10)).padStart(2,"0")]})),circoLabel=deputes.length>1?"Circonscriptions concernées":"Circonscription",cantons=cantonsForCommune(e,c),csp=state.communeCsp.get(code);return`<div class="section-block"><strong>Aide à la décision — visite gouvernementale</strong>
<div class="detail-stat"><span>Maire</span><strong>${c.maire||"Non renseigné"}</strong></div>
${csp?`<div class="detail-stat"><span>Circonscription de sécurité publique</span><strong>CSP ${csp}</strong></div>`:""}
<div class="detail-stat"><span>${circoLabel} · député${deputes.length>1?"s":""}</span>${deputes.map(d=>`<strong>${d.num}${d.num===1?"ère":"ème"} circ. — ${d.nom||"Non renseigné"}</strong>`).join("")}${deputes.length>1?"<small>Commune répartie sur plusieurs circonscriptions : vérifier le bureau de vote concerné.</small>":""}</div>
<div class="detail-stat"><span>Canton · conseiller${cantons.reduce((n,cd)=>n+cd.elus.length,0)>1?"s":""} départementa${cantons.reduce((n,cd)=>n+cd.elus.length,0)>1?"ux":"l"}</span>${cantons.length?cantons.map(cd=>`<strong>${cd.nom}</strong><small>${cd.elus.join(" · ")}</small>`).join(""):"<strong>Non renseigné</strong>"}${cantons.length>1?"<small>Commune répartie sur plusieurs cantons : vérifier le bureau de vote concerné.</small>":""}</div>
<div class="detail-stat"><span>Sénateurs du Val-d'Oise</span><small>${e.senateurs.join(" · ")}</small></div>
</div>`}
function showDetail(feature){const p=feature.properties,c=p.competence,force=c?.institution==="PN"?"Police nationale":"Gendarmerie nationale",color=c?.institution==="GN"?sectorColor(c.service):"#000091";document.getElementById("detailContent").innerHTML=`<span class="eyebrow">COMMUNE SÉLECTIONNÉE</span><h2>${p.nom}</h2><div class="detail-stat"><span>Force compétente</span><strong>${force}</strong></div><div class="detail-stat sector-detail" style="--sector:${color}"><span>${c?.institution==="GN"?"Secteur de gendarmerie":"Unité de rattachement"}</span><strong>${(c?.service||"Information indisponible").replace(/^.*? - /,"")}</strong></div><p class="detail-help">Cette commune relève territorialement de cette unité.</p>${eluBlock(p.code)}`;document.getElementById("detailPanel").classList.add("open")}
function serviceKind(item){const tags=item.tags||{};if(tags.amenity==="fire_station")return"pompiers";if(tags["police:FR"]==="police")return"commissariats";if(tags["police:FR"]==="gendarmerie")return"brigades";return null}
function serviceLabel(kind){return kind==="pompiers"?"Centre d’incendie et de secours":kind==="commissariats"?"Commissariat de Police nationale":"Caserne ou brigade de Gendarmerie nationale"}
function pointOf(item){return item.lat?[item.lat,item.lon]:item.center?[item.center.lat,item.center.lon]:null}
function showService(item,kind){const t=item.tags||{},name=t.name||t.official_name||serviceLabel(kind),osmAddress=[t["addr:housenumber"],t["addr:street"],t["addr:postcode"],t["addr:city"]].filter(Boolean).join(" "),address=osmAddress||t.ban_label||"Adresse non renseignée",city=t["addr:city"]||t.ban_city||"",phone=t.phone||t["contact:phone"]||"Non renseigné",hours=t.opening_hours||"Non renseignés";document.getElementById("detailContent").innerHTML=`<span class="eyebrow">IMPLANTATION OSM · BAN</span><h2>${name}</h2><div class="detail-stat"><span>Type de service</span><strong>${serviceLabel(kind)}</strong></div><div class="detail-stat"><span>Adresse</span><strong>${address}</strong>${city&&!address.includes(city)?`<small>${city}</small>`:""}</div><div class="detail-stat"><span>Téléphone</span><strong>${phone}</strong></div><div class="detail-stat"><span>Horaires renseignés</span><strong>${hours}</strong></div><p class="detail-help">Localisation OpenStreetMap et adresse rapprochée avec la Base Adresse Nationale. Vérifiez les conditions d’accueil avant tout déplacement.</p>`;document.getElementById("detailPanel").classList.add("open")}
function render(){if(state.territory)map.removeLayer(state.territory);if(state.cspLayer){map.removeLayer(state.cspLayer);state.cspLayer=null}state.markers.forEach(m=>map.removeLayer(m));state.markers=[];if(state.cspPolice&&state.csp)state.cspLayer=L.geoJSON(state.csp,{style:cspStyle}).addTo(map);const features=state.communes.filter(c=>c.contour).map(c=>({type:"Feature",properties:{...c,competence:state.competences.get(c.code)},geometry:c.contour}));state.territory=L.geoJSON({type:"FeatureCollection",features},{style,onEachFeature:(f,l)=>{const c=f.properties.competence,unit=c?.institution==="PN"?"Police nationale":shortService(c?.service);l.bindTooltip(`<strong>${f.properties.nom}</strong><br>${c?.institution==="PN"?"Zone Police nationale":`Secteur GN · ${unit}`}`,{sticky:true});l.on("click",()=>showDetail(f))}}).addTo(map);if(state.gendarmerieZone){const groups=new Map;state.communes.forEach(c=>{const competence=state.competences.get(c.code),point=c.centre?.coordinates;if(competence?.institution!=="GN"||!point)return;const item=groups.get(competence.service)||{lng:0,lat:0,n:0};item.lng+=point[0];item.lat+=point[1];item.n++;groups.set(competence.service,item)});groups.forEach((p,service)=>{const label=L.marker([p.lat/p.n,p.lng/p.n],{interactive:false,icon:L.divIcon({className:"sector-map-label",html:`<span style="--sector:${sectorColor(service)}">${shortService(service)}</span>`,iconSize:null})}).addTo(map);state.markers.push(label)})}state.services.forEach(item=>{const kind=serviceKind(item),point=pointOf(item);if(!kind||!point||!state[kind])return;const colors={pompiers:"#e1000f",commissariats:"#000091",brigades:"#18753c"},shapes={pompiers:6,commissariats:6.5,brigades:6.5};const m=L.circleMarker(point,{radius:shapes[kind],color:"#fff",weight:2,fillColor:colors[kind],fillOpacity:1}).bindTooltip(`<strong>${serviceLabel(kind)}</strong><br>${item.tags?.name||item.tags?.official_name||"Implantation recensée"}`).on("click",()=>showService(item,kind)).addTo(map);state.markers.push(m)})}
Promise.all([fetch("https://geo.api.gouv.fr/departements/95/communes?fields=nom,code,centre,contour").then(r=>r.json()),fetch("data/competence-police-gendarmerie.csv").then(r=>r.text()).then(parseCsv),fetch("data/osm-services.json").then(r=>r.json()),fetch("data/elus-95.json").then(r=>r.json()).catch(()=>null),fetch("data/circo-police-95.geojson").then(r=>r.json()).catch(()=>null),fetch("https://geo.api.gouv.fr/departements/95?fields=contour").then(r=>r.json()).then(d=>d.contour).catch(()=>null)]).then(([communes,competences,osm,elus,csp,deptContour])=>{addDeptMask(deptContour);state.communes=communes;state.competences=new Map(competences.map(c=>[c.code,c]));state.elus=elus;state.csp=csp;sectorNames.push(...[...new Set(competences.filter(c=>c.institution==="GN").map(c=>c.service))].sort((a,b)=>a.localeCompare(b,"fr")));state.services=osm.elements||[];document.getElementById("gendarmerieLegendItems").innerHTML=sectorNames.map(s=>`<span><i style="background:${sectorColor(s)}"></i>${shortService(s)}</span>`).join("");if(csp)communes.forEach(c=>{const pt=c.centre?.coordinates;if(!pt)return;const f=csp.features.find(ft=>pointInGeometry(pt,ft.geometry));if(f)state.communeCsp.set(c.code,f.properties.nom.charAt(0)+f.properties.nom.slice(1).toLowerCase())});render();map.fitBounds(state.territory.getBounds(),{padding:[20,20]})}).catch(()=>{});
document.querySelectorAll("[data-layer]").forEach(button=>button.addEventListener("click",()=>{const key=button.dataset.layer;state[key]=!state[key];button.classList.toggle("active",state[key]);button.setAttribute("aria-pressed",String(state[key]));if(key==="gendarmerieZone")document.getElementById("gendarmerieLegend").hidden=!state[key];render()}));
document.getElementById("resetView").addEventListener("click",()=>state.territory&&map.fitBounds(state.territory.getBounds(),{padding:[20,20]}));document.getElementById("closeDetail").addEventListener("click",()=>document.getElementById("detailPanel").classList.remove("open"));
function search(){const q=document.getElementById("searchInput").value.trim().toLocaleLowerCase("fr"),c=state.communes.find(x=>x.nom.toLocaleLowerCase("fr").startsWith(q));if(!c)return;state.territory.eachLayer(l=>{if(l.feature.properties.code===c.code)showDetail(l.feature,l)})}document.getElementById("searchButton").addEventListener("click",search);document.getElementById("searchInput").addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();search()}});
document.getElementById("openComprendre").addEventListener("click",()=>document.getElementById("comprendreDialog").showModal());document.querySelectorAll("[data-close]").forEach(b=>b.addEventListener("click",()=>document.getElementById(b.dataset.close).close()));
document.getElementById("mobileLayers").addEventListener("click",e=>{const sidebar=document.getElementById("layerSidebar"),open=sidebar.classList.toggle("open");e.currentTarget.setAttribute("aria-expanded",String(open))});
